# Generated by Django 2.2.5 on 2019-10-24 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('cuenta_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('estado', models.BooleanField(default=True)),
                ('fechaApertura', models.DateField(auto_now_add=True)),
                ('tipoCuenta', models.CharField(choices=[('corriente', 'Corriente'), ('ahorros', 'Ahorros')], default='ahorros', max_length=30)),
                ('saldo', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('transaccion_id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaTransaccion', models.DateTimeField(auto_now_add=True)),
                ('tipoTransaccion', models.CharField(choices=[('retiro', 'Retiro'), ('deposito', 'Deposito'), ('transferencia', 'Tranferencia')], default='retiro', max_length=30)),
                ('valor', models.DecimalField(decimal_places=3, max_digits=10)),
                ('descripcion', models.TextField()),
                ('responsable', models.CharField(max_length=160)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cuenta')),
            ],
        ),
    ]
