# Generated by Django 2.2.5 on 2019-10-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_cuenta_transaccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='tipoTransaccion',
            field=models.CharField(choices=[('retiro', 'Retiro'), ('deposito', 'Deposito'), ('transferencia', 'Tranferencia')], max_length=30),
        ),
    ]
