# Generated by Django 2.2.6 on 2019-11-01 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_auto_20191101_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='numero',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
