# Generated by Django 2.2.6 on 2019-11-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_auto_20191101_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='numero',
            field=models.CharField(max_length=20, unique=True, verbose_name='Numero Cuenta:'),
        ),
    ]
